[
    {
        "ID": 128397,
        "Sex": "m",
        "Has_HCM": true,
        "Sire_ID": 301486.0,
        "Sire_has_HCM": false,
        "Dam_ID": 134407.0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0,
    },
    {
        "ID": 134407,
        "Sex": "f",
        "Has_HCM": false,
        "Sire_ID": 0,
        "Sire_has_HCM": false,
        "Dam_ID": 0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0.0,
    },
    {
        "ID": 179270,
        "Sex": "f",
        "Has_HCM": true,
        "Sire_ID": 391637.0,
        "Sire_has_HCM": false,
        "Dam_ID": 284415.0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0,
    },
    {
        "ID": 185330,
        "Sex": "m",
        "Has_HCM": true,
        "Sire_ID": 289857.0,
        "Sire_has_HCM": true,
        "Dam_ID": 240916.0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0,
    },
    {
        "ID": 240916,
        "Sex": "f",
        "Has_HCM": false,
        "Sire_ID": 396336.0,
        "Sire_has_HCM": false,
        "Dam_ID": 373949.0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0,
    },
    {
        "ID": 257571,
        "Sex": "m",
        "Has_HCM": false,
        "Sire_ID": 0,
        "Sire_has_HCM": false,
        "Dam_ID": 0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0.0,
    },
    {
        "ID": 284415,
        "Sex": "f",
        "Has_HCM": false,
        "Sire_ID": 0,
        "Sire_has_HCM": false,
        "Dam_ID": 0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0.0,
    },
    {
        "ID": 289857,
        "Sex": "m",
        "Has_HCM": true,
        "Sire_ID": 257571.0,
        "Sire_has_HCM": false,
        "Dam_ID": 404550.0,
        "Dam_has_HCM": true,
        "Has_HCM_Mendel": 0,
    },
    {
        "ID": 301486,
        "Sex": "m",
        "Has_HCM": false,
        "Sire_ID": 0,
        "Sire_has_HCM": false,
        "Dam_ID": 0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0.0,
    },
    {
        "ID": 391637,
        "Sex": "m",
        "Has_HCM": false,
        "Sire_ID": 0,
        "Sire_has_HCM": false,
        "Dam_ID": 0,
        "Dam_has_HCM": false,
        "Has_HCM_Mendel": 0.0,
    },
    {
        "ID": 404550,
        "Sex": "f",
        "Has_HCM": true,
        "Sire_ID": 128397.0,
        "Sire_has_HCM": true,
        "Dam_ID": 179270.0,
        "Dam_has_HCM": true,
        "Has_HCM_Mendel": 0,
    },
]
